on: [push, pull_request]
name: Lint, test, deploy package

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - uses: abatilo/actions-poetry@v2
      - run: poetry check
      - run: make install-dev
      - run: make lint-type

  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - uses: abatilo/actions-poetry@v2
      - run: make install-dev
        name: Install package
      - run: make test

  deploy-package:
    runs-on: ubuntu-22.04
    needs: [lint, test]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: abatilo/actions-poetry@v2
      - name: Publish package
        run: poetry publish --build --username __token__ --password "${{ secrets.PYPI_PASSWORD }}"
